### ISSUE TITLE
SQLite3 is not defined with Windows 8.1 [pre-populated]

### ISSUE THREAD

**Issue by jdnichollsc** [brody2consult/cordova-sqlite-ext#1]
Hi my friend,

See please the following issue using Local and Remote Machine in Visual Studio 2013. http://screencast.com/t/vWCaGal8

List of plugins => http://screencast.com/t/pdGiwMHoaS

If you want, I can show you this project via Skype, my user is jdnichollsc and my email jdnichollsc@hotmail.com

Thanks in advance, Nicholls

**Comment by brody2consult** [comment]
Unfortunately I really cannot make any explanation from the screencast and am very busy to prepare for travel tomorrow morning. It would be best if you can try the following:

Make a fresh, clean project with this plugin and nothing else, without Ionic/Angular/ngCordova and do a simple test to load a pre-populated database and test a simple query.

Then make another fresh project with Ionic/Angular and this plugin but nothing else and do the simple test again.

Then you can start adding one thing at a time until you see when it goes wrong.

Thanks!

**Comment by jdnichollsc** [comment]
I have an error installing cordova-sqlite-ext after create the Windows "Universal" (8.1) project using litehelpers / cordova-windows-nufix

See please: http://screencast.com/t/GrgfeI320

**Comment by jdnichollsc** [comment]
More tests, see please: http://screencast.com/t/n3tzK8wtE

See the statement => http://screencast.com/t/9HRayH2P

Thanks in advance

**Comment by jocheng** [comment]
Hi  Nicholls,

it seems that you are using pre-populated database in windows Universal.
Perhaps I've found something...
In \plugins\cordova-sqlite-ext\src\windows\SQLiteProxy.js Line 61 there
is a hardcoded databasename `"pre.db"`. As stated in the readme.md:
"The pre-populated database file name must match exactly the file name given in openDatabase"
I think that here has to be placed the given database name.
So the line has to be:
`var sourceUri = new Windows.Foundation.Uri("ms-appx:///www/" + dbname);`
So you can test  in two ways. Rename your database in the www folder and in `openDatabase` to `"pre.db`" or change the line 61.

Hope this helps.

**Comment by jdnichollsc** [comment]
@jocheng Excellent my friend!! Thanks for your help! :dancers:

**Comment by brody2consult** [comment]
> In `\plugins\cordova-sqlite-ext\src\windows\SQLiteProxy.js` Line `61` there
> is a hardcoded databasename "`pre.db`".

Thanks @jocheng, you are absolutely correct and this should be _really_ easy to fix. Unfortunately I cannot test a solution until I return from vacation in early January. If someone can test and raise a fix, I would be happy to merge it. (Please raise the fix from I new branch since I would probably `git cherry-pick` it.)

**Comment by brody2consult** [comment]
> In `\plugins\cordova-sqlite-ext\src\windows\SQLiteProxy.js` Line `61` there
> is a hardcoded databasename "`pre.db`".

The fix is applied, closing.

**Comment by jdnichollsc** [comment]
Cool! :dancers:
