### ISSUE TITLE
Pre-populated sqlite db on android developer app

### ISSUE THREAD

**Issue by mamcgree** [brody2consult/cordova-sqlite-ext#10]
Greetings Chris..
 I needed to open a pre-populated sqlite db in android  I added your cordova-sqlite-ext and it worked fine when I compiled it for android.  I added it to the  "Andoid Developer App" but it will not open the existing db in the www folder using
var db = window.sqlitePlugin.openDatabase({name: "my.db", createFromLocation: 1});
 It assumes it's not there and creates a new one in the databases folder of the  Andoid Developer App.  Do have an suggestions.
Thank you in advance for your time..
Cheers..
Groetjes... (my wife is from Eindhoven)..

**Comment by brody2consult** [comment]
Hi @mamcgree,

To be honest I have never really worked with the PhoneGap Android Developer App. Can you try creating a plain Cordova app using the Cordova CLI and start with a very simple test?

The automatic test suite includes spec/www/spec/pre-populated-db-test.js which verifies that the database file is not overwritten if it is already present.

Thanks!

**Comment by mamcgree** [comment]
Hi Chris..

Thanks for the quick response..  I'm new to phonegap.  I compiled the 
developer app with your plugin, which allows the sqlite to function, but 
it doesn't handle and existing db.  Developer app does not currently 
handle sqlite.  I will poke around but I am not very experienced in this 
area.

Thanks again for your quick response..

Cheers..

**Comment by jdnichollsc** [comment]
My last template have an example :dancers:  https://github.com/jdnichollsc/Ionic-Starter-Template

**Comment by brody2consult** [comment]
Closing, this will be handled in litehelpers/Cordova-sqlite-storage#427
