### ISSUE TITLE
Prepared statement failed when swithing from sqlite-storage to sqlite-ext

### ISSUE THREAD

**Issue by ruudsilvrants** [brody2consult/cordova-sqlite-ext#11]
Greetings,

At first I would like to mention that I am relative new to cordova and the sqlite plugins.

In the documentation sqlite-storage refers to sqlite-ext if you want to use a pre-populated database. But If I adjust my plugin to sqlite-ext the following errors keeps getting up when fetching records:
W/System.err(16153): java.sql.SQLException: prepare statement failed with error: 26
W/System.err(16153):    at io.liteglue.SQLiteGlueConnection.prepareStatement(SQLiteGlueConnection.java:45)
W/System.err(16153):    at io.sqlc.SQLiteConnectorDatabase.executeSqlStatementNDK(SQLiteConnectorDatabase.java:168)
W/System.err(16153):    at io.sqlc.SQLiteConnectorDatabase.executeSqlBatch(SQLiteConnectorDatabase.java:109)
W/System.err(16153):    at io.sqlc.SQLitePlugin$DBRunner.run(SQLitePlugin.java:410)
W/System.err(16153):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err(16153):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err(16153):    at java.lang.Thread.run(Thread.java:818)

The test project is located at: https://github.com/ruudsilvrants/cordovadbtest.

Besides this error I would like to ask if using a pre-populated and implicit sqlite-ext is a good solution to the following use-case:
The project is about using +- 25.000 records offline (around 10Mb in size) and additionally updating these with information from the webserver.
What is the best solution to save/import these records in the sqlite database?
The idea was to use the pre-populated database and request the webserver for updated/changes and updating the database on the device.This, to avoid retrieving all records at first start-up.

Thanks in advance,
Ruud

**Comment by brody2consult** [comment]
@ruudsilvrants ik geef mijn excuses. Is this still an issue for you? Did you already find a solution?

To be honest, I would favor downloading all of the records from the web server. I added the pre-populated database functionality due to popular demand.

In general a prepare statement failure means that you attempted to use an invalid table or column name.

Please let me know if you still want me to take a look at the test project. Thanks.
