### ISSUE TITLE
Using More than One Database in Ionic Question

### ISSUE THREAD

**Issue by coommark** [brody2consult/cordova-sqlite-ext#14]
Is it possible to use more than 1 database in Ionic? I have been having weird experiences with the core [https://github.com/litehelpers/Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) where even when I substitute the db with another one of different name, it still loads the first one (was using [https://github.com/an-rahulpandey/cordova-plugin-dbcopy](https://github.com/an-rahulpandey/cordova-plugin-dbcopy). Has anyone ever tried using two or more dbs?

**Comment by brody2consult** [comment]
Sorry for the delay, this sounds _really_ strange.

I would need a test application to reproduce this issue. It would be best if you can build a new version and post it as a project for me to play with.

For this case you can also send a version privately to: brodybits@litehelpers.net
