### ISSUE TITLE
Visual Studio 2015 and apache cordova project

### ISSUE THREAD

**Issue by mgomez-dgt** [brody2consult/cordova-sqlite-ext#15]
------ Build started: Project: Magic, Configuration: Debug Windows-x86 ------
  Your environment has been set up for using Node.js 0.12.2 (ia32) and npm.
  ------ Ensuring correct global installation of package from source package directory: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\ApacheCordovaTools\packages\vs-tac
  ------ Name from source package.json: vs-tac
  ------ Version from source package.json: 1.0.37
  ------ Package already installed globally at correct version.
  ------ Cordova tools 6.0.0 already installed.
  ------ Build Settings:
  ------ Build Settings:
  ------    platformConfigurationBldDir: C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\bld\Windows-x86\Debug
  ------    platformConfigurationBinDir: C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\bin\Windows-x86\Debug
  ------    buildCommand: build
  ------    platform: Windows-x86
  ------    cordovaPlatform: windows
  ------    configuration: Debug
  ------    cordovaConfiguration: Debug
  ------    projectName: Magic
  ------    projectSourceDir: C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic
  ------    npmInstallDir: C:\Users\mgome\AppData\Roaming\npm
  ------    buildTarget: LocalMachine
  ------    language: en-US
  ------ Platform windows already exists
  ------ Copying native files from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\native\windows to platforms\windows
  ------ Copied C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\native\windows\CordovaApp.pfx to platforms\windows\CordovaApp.pfx
  ------ Done copying native files to platforms\windows
  ------ Updating plugins
  ------ Currently installed plugins: cordova-plugin-dialogs@1.2.0,cordova-plugin-file@4.1.1,cordova-plugin-file-transfer@1.5.0,cordova-plugin-network-information@1.2.0,cordova-plugin-whitelist@1.2.1,cordova-sqlite-ext@0.8.4
  ------ Currently installed dependent plugins:
  ------ Currently configured plugins:
  ------ Preparing platform: windows
  Executing "before_prepare"  hook for all plugins.
  Executing "before_build"  hook for all plugins.
  Searching PlatformJson files for differences between project vs. platform installed plugins
  No differences found between project and windows platform. Continuing...
  Generating config.xml from defaults for platform "windows"
  Found "merges" for windows platform. Copying over existing "www" files.
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Square150x150Logo.scale-100.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Square150x150Logo.scale-100.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Square150x150Logo.scale-240.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Square150x150Logo.scale-240.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Square30x30Logo.scale-100.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Square30x30Logo.scale-100.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Square310x310Logo.scale-100.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Square310x310Logo.scale-100.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Square44x44Logo.scale-100.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Square44x44Logo.scale-100.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Square44x44Logo.scale-240.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Square44x44Logo.scale-240.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Square70x70Logo.scale-100.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Square70x70Logo.scale-100.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Square71x71Logo.scale-100.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Square71x71Logo.scale-100.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Square71x71Logo.scale-240.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Square71x71Logo.scale-240.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\StoreLogo.scale-100.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\StoreLogo.scale-100.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\StoreLogo.scale-240.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\StoreLogo.scale-240.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Wide310x150Logo.scale-100.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Wide310x150Logo.scale-100.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\icons\windows\Wide310x150Logo.scale-240.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\Wide310x150Logo.scale-240.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\screens\windows\SplashScreen.scale-100.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\SplashScreen.scale-100.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\screens\windows\SplashScreen.scale-240.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\SplashScreenPhone.scale-240.png
  Copying image from C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\res\screens\windows\SplashScreenPhone.scale-240.png to C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\images\SplashScreenPhone.scale-240.png
  Updated project successfully
  Executing "pre_package"  hook for all plugins.
  Executing "after_prepare"  hook for all plugins.
  ------ Copied C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\bin\Windows-x86\Debug\Microsoft.AppxPackage.Metadata.Overrides.props to platforms\windows\Microsoft.AppxPackage.Metadata.Overrides.props
  ------ Building platform: windows
  Debug
  ------ Build configuration options: --debug
  Executing "before_compile"  hook for all plugins.
  Reading build config file: C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\build.json
  Searching for available MSBuild versions...
  Found MSBuild v4.0 at C:\Windows\Microsoft.NET\Framework\v4.0.30319\
  Found MSBuild v12.0 at C:\Program Files (x86)\MSBuild\12.0\bin\
  Found MSBuild v14.0 at C:\Program Files (x86)\MSBuild\14.0\bin\
  Building project: C:\Users\mgome\documents\visual studio 2015\Projects\Magic\Magic\platforms\windows\CordovaApp.Windows10.jsproj
    Configuration : debug
    Platform      : x86
    Constants.cpp
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\constants.cpp(1): warning C4627: '#include "Constants.h"': skipped when looking for precompiled header use [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\constants.cpp(1): note: Add directive to 'pch.h' or rebuild precompiled header
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\constants.cpp(2): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "pch.h"' to your source? [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    Database.cpp
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\database.cpp(1): warning C4627: '#include "Winerror.h"': skipped when looking for precompiled header use [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\database.cpp(1): note: Add directive to 'pch.h' or rebuild precompiled header
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\database.cpp(3): warning C4627: '#include "Database.h"': skipped when looking for precompiled header use [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\database.cpp(3): note: Add directive to 'pch.h' or rebuild precompiled header
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\database.cpp(4): warning C4627: '#include "Statement.h"': skipped when looking for precompiled header use [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\database.cpp(4): note: Add directive to 'pch.h' or rebuild precompiled header
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\database.cpp(56): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "pch.h"' to your source? [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    Statement.cpp
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\statement.cpp(1): warning C4627: '#include "Winerror.h"': skipped when looking for precompiled header use [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\statement.cpp(1): note: Add directive to 'pch.h' or rebuild precompiled header
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\statement.cpp(3): warning C4627: '#include "Statement.h"': skipped when looking for precompiled header use [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\statement.cpp(3): note: Add directive to 'pch.h' or rebuild precompiled header
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\statement.cpp(4): warning C4627: '#include "Database.h"': skipped when looking for precompiled header use [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\statement.cpp(4): note: Add directive to 'pch.h' or rebuild precompiled header
c:\users\mgome\documents\visual studio 2015\projects\magic\magic\plugins\cordova-sqlite-ext\src\windows\sqlite3-win-rt\sqlite3\statement.cpp(91): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "pch.h"' to your source? [C:\Users\mgome\Documents\Visual Studio 2015\Projects\Magic\Magic\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
    Generating Code...
ERROR building one of the platforms : error C: \Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1
  You may not have the required environment or OS to build this project
MSBUILD : cordova-build error : Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1
MDAVSCLI : error C: \Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by mgomez-dgt** [comment]
help please!

**Comment by brody2consult** [comment]
Please specify the command you used to build the project.

You may want to try opening the generated Visual Studio solution, build and run it from there.

**Comment by mgomez-dgt** [comment]
Build in Visual Studio 2015 community, Debug | Windows-x86 | Local Machine

Windows Target Version: Windows 10.0 in config.xml

$ cordova plugin list

cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.0 "File Transfer"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-sqlite-ext 0.8.4 "Cordova sqlite storage plugin with extras"
cordova-sqlite-storage 0.8.2 "Cordova sqlite storage plugin (core version)"

**Comment by brody2consult** [comment]
Fix is in PR #16, will be included soon.

**Comment by brody2consult** [comment]
The fix in PR #16 is now included (by `git cherry-pick`), thanks for reporting!
