### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by hypery2k** [brody2consult/cordova-sqlite-ext#18]
Are there any plans to support OS X, see https://cordova.apache.org/announcements/2016/02/16/osx-4.0.0.html

**Comment by brody2consult** [comment]
This is under consideration. For priority feature development and support please reach out to: sales@litehelpers.net

**Comment by mattlanham** [comment]
👍

**Comment by hypery2k** [comment]
You can use the iOS Files directly. Just copied them and seem to work so far

**Comment by brody2consult** [comment]
macOS (nee OSX) is now supported, please report if you guys have any questions
