### ISSUE TITLE
Pre populated databases do not get copied on Windows universal 

### ISSUE THREAD

**Issue by sachithd** [brody2consult/cordova-sqlite-ext#19]
Please note that this issue is only related to windows universal platform 

The pre populated database is in www directory and the following tests were done on Windows 10 emulator through Visual Studio 2015
1. To start with the plugin docs states that the pre populated db can be initialized as below.
   `var db = window.sqlitePlugin.openDatabase({name: "my.db", createFromLocation: 1});`
   But this gives the following error 
   
   > Error: Database location or iosDatabaseLocation value is now mandatory in openDatabase call
2. If I open the db as `window.sqlitePlugin.openDatabase({name: 'mydb.db',location: 0}` it will output the following on the console. 
   
   > OPEN database: mydb.db
   > open db name: mydb.db at full path: C:\Data\Users\DefApps\AppData\Local\Packages\com.packagename.etc_XXXXXX\LocalState\mydb.db
3. When I perform a select query on the database it gives
   
   > sql exception error: Error preparing an SQLite statement

I have tried executeSql as well as running executeSql inside a transaction but experienced the same result.

4.But when I run a create table query, instead of the select query, it works fine. So after running few queries such as "pragma page_count" it is clear that the pre populated database was not copied/created on the device. Instead it has created an empty database in the above path. I have also tried opening  database with different locations, on different emulators, also by deleting the app but nothing worked.

5.The size of the database is about 10mb. Is there a limitation to the database size on Windows? I haven't tested this plugin with a small sized database but this works well on both Android and iOS with the same database. (actually I have used the basic version of this plugin litehelpers/Cordova-sqlite-storage for android and ios)

Please advise if anyone is aware of this issue and can be fixed through my code/plugin or if its a limitation on Windows platform.

Thanks

**Comment by brody2consult** [comment]
I think you have the wrong version installed (or have multiple versions installed). Please check your plugins very carefully, remove any and all versions of Cordova sqlite plugin(s), and install this version to get pre-populated databases working with Windows 10.

**Comment by brody2consult** [comment]
> 5.The size of the database is about 10mb.

That should be no problem!

**Comment by sachithd** [comment]
Thanks for the reply. These are my plugins list

> cordova-plugin-admobpro 2.14.0 "AdMob Plugin Pro"
> cordova-plugin-console 1.0.2 "Console"
> cordova-plugin-extension 1.3.0 "Cordova Plugin Extension"
> cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
> cordova-plugin-splashscreen 3.2.1 "Splashscreen"
> cordova-plugin-statusbar 2.1.2 "StatusBar"
> cordova-plugin-whitelist 1.2.1 "Whitelist"
> cordova-plugin-x-socialsharing 5.0.12-dev "SocialSharing"
> cordova-sqlite-ext 0.8.6 "Cordova sqlite storage plugin with extras"

I have also tried removing / adding the cordova-sqlite-ext plugin several times and also tried removing / adding the windows platforms before I raised this issue.

**Comment by brody2consult** [comment]
This is already covered by the test suite. Can you post a very simple project that demonstrates your issue? (Please get rid of the other plugins as much as possible.)

**Comment by sachithd** [comment]
after lot of testing I have found out that the issue is related to the version **0.8.6**. When I tried the version 0.8.4 the database was copied successfully.

**Comment by brody2consult** [comment]
Thanks @sachithd for reporting this. Version **0.8.6** was released based on the wrong branch and should NOT be used. I expect to release a new version based on the default branch sometime later today.

**Comment by sachithd** [comment]
No problem and thanks for your help.

**Comment by rsalt** [comment]
Hi Chris,
had using our Windows Phone Universal ( 8.1 ) d 
cordova-sqlite-ext@0.8.4 verison for prepoluated db.

also try to install latest release but m getting the db open error with it i.e. version ( 0.10.5, 0.10.4 )

1. Open is get success message ie.
but for Sql Execusiion getting error ie.


- sql exception error: Error preparing an SQLite statement.
- db error:{"db":{"openargs":{"name":"edm_app.db","location":2,"createFromLocation":1,"dblocation":"nosync","createFromResource":"1"},"dbname":"edm_app.db"},"txlock":true,"readOnly":false,"executes":[]}
- db error:{"description":"a statement error callback did not return false: Error preparing an SQLite statement.","code":-1,"stack":"Error: a statement error callback did not return false: Error preparing an SQLite statement.\n   at SQLitePluginTransaction.prototype.handleStatementFailure (ms-appx://io.cordova.windowsappca/www/plugins/cordova-sqlite-ext/www/SQLitePlugin.js:392:7)\n   at Anonymous function (ms-appx://io.cordova.windowsappca/www/plugins/cordova-sqlite-ext/www/SQLitePlugin.js:411:13)\n   at mycb (ms-appx://io.cordova.windowsappca/www/plugins/cordova-sqlite-ext/www/SQLitePlugin.js:455:13)\n   at cordova.callbackFromNative (ms-appx://io.cordova.windowsappca/www/cordova.js:293:41)\n   at cordova.callbackSuccess (ms-appx://io.cordova.windowsappca/www/cordova.js:273:9)\n   at onSuccess (ms-appx://io.cordova.windowsappca/www/cordova.js:875:17)\n   at Anonymous function (ms-appx://io.cordova.windowsappca/www/plugins/cordova-sqlite-ext/src/windows/sqlite-proxy.js:160:4)"}
 
var db = window.sqlitePlugin.openDatabase({name: "edm_app.db", location: 2, createFromLocation: 1});
                var edmDB = this;
                /*if (typeof common == "undefined") {
                    common = commonParam;
                }*/
                //alert("before redirect");
                db.transaction(function(tx) {
                    var qur = "SELECT * FROM dif_user_info";
                    tx.executeSql(qur, [], function(tx, result) {
                        if (result.rows.length > 0) {
                            require(["app", "apps/offlinePin/offlinePin_app"], function(App) {
                                App.execute("offlinePin:show");
                            });

                        } else {
                            /* require(["app", "apps/login/login_app"], function(App) {
                                App.execute("login:show");
                            });*/
                            require(["apps/agentRegistration/agentRegistration_app"], function() {
                                App.execute("agentRegistration:show");
                                App.navigate("agentRegistration");
                            });
                            common.closeLoader();
                        }

                        //edmDB.getUserInfo(tx,result,edmDB)
                    }, edmDB.errorCB);
                }, edmDB.errorCB, edmDB.successCB);

Please advise, 
thanks & Regards,

**Comment by brody2consult** [comment]
Hi @rsalt this issue was about a different question that was already resolved, closing.

To answer your question: Windows 8.1 is no longer supported by this project. You *may* be able to get it to work with an older version of this plugin but I generally do not support these. I *may* continue to support pre-populated databases with Windows 8.1 in case there is sufficient demand from the user community. Otherwise you may want to look at some other options described in litehelpers/Cordova-sqlite-help#26.

In case you decide to use this plugin version with a supported platform such as Windows 10, you may want to use <https://github.com/brodybits/cordova-sqlite-ext-bootstrap-starter-app> as a starting point.
