### ISSUE TITLE
Running on windows 10, cannot open database

### ISSUE THREAD

**Issue by shady786** [brody2consult/cordova-sqlite-ext#20]
When running on local machine / emulator works perfectly.  Remotely debugging or installing appx package on tablet is throwing cannot open database error.

Looks like a permission error somewhere ?

Get this using a newly created project and adding only sqlite-ext plugin through cordova cli.

**Comment by brody2consult** [comment]
Unfortunately this is not enough information to find the cause. Please show all log output and also the results of JSON.stringify(e) (where e is the exception object that is thrown).

**Comment by shady786** [comment]
Hi

So I have built the app using cordova build windows --release --archs="x86"

It works when running on my local and simulator.

When signing and deploying to a device or using remote deployment from VS I get this : 

OPEN database: hello-world.db
open db name: hello-world.db at full path: C:\Users\shady786\AppData\Local\Packages(ommitted)\LocalState\hello-world.db
OPEN database: hello-world.db failed, aborting any pending transactions
Could not open database

It's worth noting I get the very same when running a clean project and doing the deployment.  Runs fine on my local and sim, but cannot create db in that LocalState folder

Thanks

**Comment by brody2consult** [comment]
I just published a new version. Can you try the following:
- try with both debug and release build
- try with x64 (x86-64)?
- Did you try it on a Windows Mobile device? It works for me when I run it from Visual Studio 2015 (enable developer mode on both "workstation" and mobile device)

**Comment by shady786** [comment]
Hi

Debug versions deployed to device are now working, thanks.  Release versions are still as before.

No issues when trying both debug / release on sim or local.  Only having this issue when deploying via visual studio or app package onto actual device. Release build is now the only issue.

**Comment by brody2consult** [comment]
Do you still have this problem?

If yes, please try it with a very simple test program. If you have this problem with a very simple test program, please post it.

I have run the test suite on a Windows 10 release build on my Lumia AMD device with no problems.

**Comment by shady786** [comment]
It is working as expected now.  Thanks
