### ISSUE TITLE
Unable to execute sql query in windows 10 UWP

### ISSUE THREAD

**Issue by pradeep0508** [brody2consult/cordova-sqlite-ext#21]
I'm getting below exception when I tried execute below query from existing database. 

"Object doesn't support property or method 'executeSql'"

I used below code for testing.

```
       var db1 = window.sqlitePlugin.openDatabase({ name: 'mosaic_app', location: 0 });
        db1.executeSql("SELECT LENGTH('tenletters') AS stringlength", [], function (res) {
            console.log('got stringlength: ' + res.rows.item(0).stringlength);
        }, function (error) {
            console.log('SELECT error: ' + error.message);
        });
```

What I'm doing wrong?

**Comment by brody2consult** [comment]
It looks like there is something really strange about your installation. Please try this with a fresh new test project and a fresh new installation of this plugin, _with no other plugins installed_, and try the echoTest as well.

If you continue to see this issue in a fresh new project then please share it and I will take a look.
