### ISSUE TITLE
Building wp10 with this plugin installed give me errors

### ISSUE THREAD

**Issue by Bandito11** [brody2consult/cordova-sqlite-ext#25]
Works before installing plugin but after gives me error. 

Using cordova 6.1. 
https://cdn.discourse.org/ionicframework/uploads/default/original/3X/e/4/e4a32743ce31f74b371fd65ef44969293a927d47.PNG

**Comment by brody2consult** [comment]
You have to specify the CPU type. I will document this when I get a chance.

**Comment by Bandito11** [comment]
This was tested and built on a win10 x86 and x64 architecture

**Comment by brody2consult** [comment]
I meant that you have to specify the target cpu architecture, which is arm
for most mobile devices.
