### ISSUE TITLE
Using pre-populated DB

### ISSUE THREAD

**Issue by FaraTar** [brody2consult/cordova-sqlite-ext#27]
Hi,
I want to write an application with a pre- populated db. There for I used the  cordova-sqlite-ext

There for I tried the quickstart guid and it went well. If I create a db on start up  it went well, too. 
But If I try to use my db  in the www directory, I get an error evry time I tries to insert code in an existing table. 

`var db = window.sqlitePlugin.openDatabase({ name: "Orders.db", location: 1, createFromLocation: 1 });

```
    db.transaction(function (tx) {
        tx.executeSql('DROP TABLE IF EXISTS tb_auftrag');
        tx.executeSql('CREATE TABLE IF NOT EXISTS tb_auftrag (auftragid integer primary key, kdnr integer)');


        tx.executeSql("INSERT INTO tb_auftrag (auftragid, kdnr) VALUES (?,?)", [12356, 100], function (tx, res) {
            console.log("insertId: " + res.insertId + " -- probably 1");
            console.log("rowsAffected: " + res.rowsAffected + " -- should be 1");

            db.transaction(function (tx) {
                tx.executeSql("select auftragid, kdnr from tb_auftrag;", [], function (tx, res) {
                    console.log("res.rows.length: " + res.rows.length );
                    for (i = 0; i <= res.rows.length;i++){
                    console.log("res.rows.item("+i+").auftragid: " + res.rows.item(i).auftragid);
                    console.log("res.rows.item("+i+").kdnr: " + res.rows.item(i).kdnr);
                        }
                },
                function (e) { console.log("Select Error:" + e.message) });

            });

        }, function (e) {
            console.log("ERROR: " + e.message);
        });

    });`
```

This code works well.

If I set the DROP and CREATE statements to comment I can use the database created once and manipulate and read the data. 

But the select ignores all inputs created with SQLiteBrowser in the prepopulated DB and also if I browse the db in www folder I only get the inputs I created with the SQLiteBrowser.

I tried the cordova-plugin-dbcopy to set the db in to the correct directory and I get the responses the db still exists. 

If I set this code  in front of the code above

`var dbname = "Orders.db";
        var location = 0;
        var success = function (e) { console.log("success copy: " + e.message); }
        var error = function (e) { console.log("error copy: " + e.message); }
        window.plugins.sqlDB.remove(dbname, location, success, error);
        window.plugins.sqlDB.copy(dbname, location, success, error);`

I get an error on using INSERT and SELECT when not using DROP and or CREATE table.

I hope someone has a soloution for my issue.

Thank you for your respond.

**Comment by brody2consult** [comment]
On May 4, 2016 6:06 PM, "FaraTar" notifications@github.com wrote:

> Hi,
> I want to write an application with a pre- populated db. There for I used
> the cordova-sqlite-ext
> 
> There for I tried the quickstart guid and it went well. If I create a db
> on start up it went well, too.
> But If I try to use my db in the www directory, I get an error evry time
> I tries to insert code in an existing table.
> 
> `var db = window.sqlitePlugin.openDatabase({ name: "Orders.db", location:
> 1, createFromLocation: 1 });
> 
> ```
> db.transaction(function (tx) {
>     tx.executeSql('DROP TABLE IF EXISTS tb_auftrag');
>     tx.executeSql('CREATE TABLE IF NOT EXISTS tb_auftrag (auftragid
> ```
> 
> integer primary key, kdnr integer)');
> 
> ```
>     tx.executeSql("INSERT INTO tb_auftrag (auftragid, kdnr) VALUES
> ```
> 
> (?,?)", [12356, 100], function (tx, res) {
>             console.log("insertId: " + res.insertId + " -- probably 1");
>             console.log("rowsAffected: " + res.rowsAffected + " -- should
> be 1");
> 
> ```
>         db.transaction(function (tx) {
>             tx.executeSql("select auftragid, kdnr from tb_auftrag;",
> ```
> 
> [], function (tx, res) {
>                     console.log("res.rows.length: " + res.rows.length );
>                     for (i = 0; i <= res.rows.length;i++){
>                     console.log("res.rows.item("+i+").auftragid: " +
> res.rows.item(i).auftragid);
>                     console.log("res.rows.item("+i+").kdnr: " +
> res.rows.item(i).kdnr);
>                         }
>                 },
>                 function (e) { console.log("Select Error:" + e.message)
> });
> 
> ```
>         });
> 
>     }, function (e) {
>         console.log("ERROR: " + e.message);
>     });
> 
> });`
> ```
> 
> This code works well.
> 
> If I set the DROP and CREATE statements to comment I can use the database
> created once and manipulate and read the data.

I think I can understand up to here.

> But the select ignores all inputs created with SQLiteBrowser in the
> prepopulated DB and also if I browse the db in www folder I only get the
> inputs I created with the SQLiteBrowser.

I am not sure if I understand this part 100%.

Keep in mind that this plugin only reads the pre-populated database the
first time you run the app unless you erase the app data. To test the
pre-populated database step or is recommended to delete and reinstall your
app.

Also the database is copied from the www directory. The database in the www
directory will never be overwritten.

> I tried the cordova-plugin-dbcopy to set the db in to the correct
> directory and I get the responses the db still exists.

I am not sure if I can follow this part.

As a general comment I included the pre-populated database feature due to
popular demand. I would personally favor populating the database from a
dump or fetching the data over HTTP instead.

**Comment by FaraTar** [comment]
Thank you for your fast response.

I am sorry for writting kind a confused. 

Allright  I' ll take  your  soloution to use a dump file.

Thanks again.
