### ISSUE TITLE
[Ionic pitfall] Error installing with Cordova CLI tool

### ISSUE THREAD

**Issue by jdnichollsc** [brody2consult/cordova-sqlite-ext#3]
Hi guys,

I created an empty Ionic Project and after run the command to install the plugin with Cordova CLI, I'm debugging with GapDebug in the mobile and I see that window.sqlitePlugin is undefined.

See please: http://screencast.com/t/a0Fd3IeRr

**Comment by brody2consult** [comment]
I am suspicious that the code is run before the 'deviceready' event. I have seen this problem with an Ionic app before.
