### ISSUE TITLE
new transaction is waiting for open operation

### ISSUE THREAD

**Issue by Vishal-Isharani** [brody2consult/cordova-sqlite-ext#31]
Hello @brodybits ,

Hope you are doing well.

I have integrated this plugin in my ionic application it works like charm.

But suddenly i am getting this console log 
"new transaction is waiting for open operation"

![image](https://cloud.githubusercontent.com/assets/10386581/15328645/3941cdea-1c73-11e6-9a44-bb704aa4d68f.png)

here is my code 

```
 if (window.sqlitePlugin !== undefined) {
        db = window.sqlitePlugin.openDatabase({ name: "Jewellary.db", location: 2, createFromLocation: 1 ,androidDatabaseImplementation: 2});

}
```

Here db is variable which will be use as for firing queries in application 
and following is my code to fire queries

```
 var user_Query = "SELECT * FROM setting WHERE id = 1 AND is_valid = 1";
        $cordovaSQLite.execute(db, query, []).then(function (res) {
          console.log("success" );
          if (res.rows.length > 0) {
            is_valid = true;
          } else {
            is_valid = false;
          }
        })
```

**Comment by brody2consult** [comment]
If you use a pre-populated database it can take some time (maybe a few seconds or so) for the database to be opened properly. If you attempt to access the database before it has been properly opened you will get this message. Once the database is opened you will get the "DB opened" log message (which I do see in your console) and then the execute sql should work OK.

If you are not sure you may want to add an error handler to your execute sql function call.

Also did you try the self test functions?

**Comment by Vishal-Isharani** [comment]
Hello @brodybits  
        Thank You Very much, I am Able To Solve The Problem After Your Guidness.

**Comment by broncha** [comment]
@brodybits so how do you know if the database has opened? I check for schema version after `window.sqlitePlugin.openDatabase` and I get this.

**Comment by broncha** [comment]
nevermind, just found the doc about success callback :)
