### ISSUE TITLE
Device stop working after query

### ISSUE THREAD

**Issue by german-bortoli** [brody2consult/cordova-sqlite-ext#36]
I am having an issue, I am using ioinic2 (witu SqlStorage) and I am having an issue selecting a row using a couple of JOINS, the query is not big, also I was having an issue selecting 200 records from a single table.

The application just quit and exit.

**Comment by german-bortoli** [comment]
I discovered the problem, the encoding, when I have rows using UTF-8 characters, like á, í, ñ ... the device stop working, is there any configuration  to set in there ?

**Comment by brody2consult** [comment]
Please try using `androidDatabaseImplementation: 2` in the openDatabase call, as documented in README.md, and report if it solves the problem or not. This may be a bug in the underlying Android-sqlite-connector/Android-sqlite-native-driver libraries.

**Comment by german-bortoli** [comment]
Yes it is working now, thanks
