### ISSUE TITLE
Work on android not on ios

### ISSUE THREAD

**Issue by kountouretis** [brody2consult/cordova-sqlite-ext#37]
I use this plugin to build android and ios app. i used angularjs and cordova. The android app work perfect but the ios not work at the pages which must select from sqlite. My code is : 

```
 var statement = "";
    db.transaction(function (tx) {
    statement = "select * from pictures where objectid='"+$scope.Axiotheata.OBJECTID+"'";
    tx.executeSql(statement, [], function (tx, res) {

        for(var i=0;i<res.rows.length;i++){

            $scope.AxiotheataImagesArray[i]=res.rows.item(i);
            $scope.$apply();
        }
    }, function (e) {
        alert("Something went wrong");

    });

}, function (e) {
    alert('transaction error: ' + e.message);
  });
```

It is my first time that use this plugin and make app. Is there any solution about this? Thanks in advance.

**Comment by brody2consult** [comment]
Hi @kountouretis,

Use with Ionic and other forms of Angular are no longer supported for free. To purchase support for use with Ionic/Angular please contact: sales@litehelpers.net
