### ISSUE TITLE
When should i call db.close() and  openDatabase ?

### ISSUE THREAD

**Issue by MehdiZonjy** [brody2consult/cordova-sqlite-ext#4]
Is it efficient to call openDatabase and db.close in the onPause and onResume handlers for the application lifecycle? This way i can create a single and global Db instance that i use for all of my transactions.
the other approach would be to create a new Db instance before any transaction and close it in the transaction onSuccess/orError callbacks

which approach is better?

**Comment by brody2consult** [comment]
#### Alternative 1:

> Is it efficient to call openDatabase and db.close in the onPause and onResume handlers for the application lifecycle? This way i can create a single and global Db instance that i use for all of my transactions.

You _could_ follow this approach. I would recommend that you keep your own state whether or not you have a valid db handle, and simply (re)open the database in case you don't.

#### Alternative 2:

> the other approach would be to create a new Db instance before any transaction and close it in the transaction onSuccess/orError callbacks

Also possible, though it would introduce some overhead if your app does this frequently (though maybe not so serious these days).

#### Recommended approach

In general it is no problem to open a sqlite database and never close it, ref: https://stackoverflow.com/questions/9561832/what-if-i-dont-close-the-database-connection-in-python-sqlite/9613153#9613153

I would simply keep the database object open.

**Comment by MehdiZonjy** [comment]
i got it, thanks
