### ISSUE TITLE
Can we read sqlite files under a folder in an absolute path, such as /mnt/sdcard on android

### ISSUE THREAD

**Issue by rozhao2** [brody2consult/cordova-sqlite-ext#41]
Dears,

I read data from sqlite file in this great plugin, however, now, there are some special situations, I must load a pre-populated sqlite file from other location, such as /mnt/sdcard on android.

openDatabase function has locaiton parameter, default , 1 and 2, can we assign an absolute sqlite file path?

Thanks.

**Comment by rozhao2** [comment]
can I rewrite 

```
void open(File dbfile) throws Exception {
    dbFile = dbfile; // for possible bug workaround
    mydb = SQLiteDatabase.openOrCreateDatabase(dbfile, null);
}
```

at this place, let dbfile point to an absolute file path, 

dbFile = new File(Environment.getExte‌​rnalStorageDirectory(‌​).getAbsolutePath() + "/test_db/" + dbFile)

is this reasonable ? or is there any permission problem?

thank you very much.

**Comment by brody2consult** [comment]
It is recommended to use the File API for this. I hope to make a sample for this.
