### ISSUE TITLE
When I query sqlite multithread,android app crashed

### ISSUE THREAD

**Issue by rozhao2** [brody2consult/cordova-sqlite-ext#46]
when query sqlite multithread, (javascript event trigger asynchronized, I didn't try to control it in javascript, then it crashed sometimes, and more query times happened, crash times increase.

crash information:

    11-25 22:04:18.145     517-1017/? A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa4bae49a in tid 1017 (pool-1-thread-5)
    11-25 22:04:18.248      329-329/? I/DEBUG﹕ Build fingerprint: 'AUTOID/msm8916_d510p/msm8916_d510p:5.1.1/V1.1.2/V1.1.2:user/dev-keys'
    11-25 22:04:18.249      329-329/? I/DEBUG﹕ Revision: '0' 
    11-25 22:04:18.249      329-329/? I/DEBUG﹕ ABI: 'arm'
    11-25 22:04:18.249      329-329/? I/DEBUG﹕ pid: 517, tid: 1017, name: pool-1-thread-5  >>> com.ionicframework.electriclab474915 <<<
    11-25 22:04:18.249      329-329/? I/DEBUG﹕ signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa4bae49a
    11-25 22:04:18.271      329-329/? I/DEBUG﹕ r0 a4bae482  r1 e17c06b4  r2 00000000  r3 00000001
    11-25 22:04:18.271      329-329/? I/DEBUG﹕ r4 ab8a6540  r5 e17c06b4  r6 ab8a6b40  r7 ab8a65c0
    11-25 22:04:18.271      329-329/? I/DEBUG﹕ r8 0000001b  r9 000002c9  sl 3b9aca00  fp e17c07d4
    11-25 22:04:18.271      329-329/? I/DEBUG﹕ ip 00000000  sp e17c06b0  lr e54baaa9  pc e54ba9ec  cpsr 200f0030
    11-25 22:04:18.272      329-329/? I/DEBUG﹕ backtrace:
    11-25 22:04:18.272      329-329/? I/DEBUG﹕ #00 pc 000179ec  /data/app/com.ionicframework.electriclab474915-2/lib/arm/libsqlc-native-driver.so
    11-25 22:04:18.272      329-329/? I/DEBUG﹕ #01 pc 00017aa5  /data/app/com.ionicframework.electriclab474915-2/lib/arm/libsqlc-native-driver.so
    11-25 22:04:18.272      329-329/? I/DEBUG﹕ #02 pc 0002e5f3  /data/app/com.ionicframework.electriclab474915-2/lib/arm/libsqlc-native-driver.so
    11-25 22:04:18.272      329-329/? I/DEBUG﹕ #03 pc 00055a8f  /data/app/com.ionicframework.electriclab474915-2/lib/arm/libsqlc-native-driver.so
    11-25 22:04:18.272      329-329/? I/DEBUG﹕ #04 pc 00057901  /data/app/com.ionicframework.electriclab474915-2/lib/arm/libsqlc-native-driver.so
    11-25 22:04:18.272      329-329/? I/DEBUG﹕ #05 pc 00057b71  /data/app/com.ionicframework.electriclab474915-2/lib/arm/libsqlc-native-driver.so`
    
So, I add synchronized keyword before executeSQLiteStatement method in SQLiteConnectorDatabase.java, the app doesn't crash now... However, queries become very very slow....

Any suggestions? Thanks.

**Comment by brody2consult** [comment]
Thanks @Cicero-Zhao for reporting this issue. I do not recall seeing this exact issue before. In general the Android implementation runs a single thread for each database file. All operations on a database from JavaScript are put into a queue that that is consumed by a single thread. Also JavaScript is generally single threaded and event driven.

I would really need some more information to help diagnose this issue and find the underlying cause. I would probably need a test program, posted in a public location in case of free support.

Also I generally do not support use with Ionic for free. For free support I suggest you try doing something similar outside of Ionic and see if you continue to encounter the same issue or not. If not then you can try one thing at a time until you figure out what does and does not work.

For professional support you may contact me at: <brodybits@litehelpers.net> or <sales@litehelpers.net>.

**Comment by rozhao2** [comment]
thanks @boberbober ,I will investigate this issue for more information, after all, you suggest me to use this this plugin by a single thread, it is an important suggestion, thank you very much.

**Comment by rozhao2** [comment]
At last, the app never crashes after adding synchronized, the reason of query becomes slow is my SQL's performance is poor, after optimized SQL, it becomes very very fast.

close this issue, thank you.
