### ISSUE TITLE
possible memory overload?

### ISSUE THREAD

**Issue by ghost** [brody2consult/cordova-sqlite-ext#47]
Hi Chris,
Thanks for the plugin - it definitely helps make things a bit easier. I have searched around internet and it looks like there is no info about memory overload using cordova-sqlite-ext. I've been working on a bible readings app testing mostly with Web SQL (window.openDatabase) in Chrome browser and it works quite well (it's much faster for testing); when I compile it to android it also starts working but suddenly stops after the alert (see below - this is how I tested it). The sqlite database "bible.db" is around 32MB, and there are 3 to 4 sql requests to the database every time the function is called.  Like I said it works well in the browser; also, I tested opening small amounts of data and it works most of the time (like only one of the 3 or 4 requests - to get one reading). It also displays everything up to and including "alert("it stops after this");".  I will continue to test it out, but any advice would be appreciated - I will also leave an update if I find a solution. I hope there is enough info here - I am new to Cordova though.

```
`
document.addEventListener("deviceready", onDeviceReady, false);
var db;

function onDeviceReady() {
db = window.sqlitePlugin.openDatabase({name: 'bible.db', location: 'default', createFromLocation: 1});
}



function yayB(day){   //a datepicker calls on yayB() and passes in the day as a date

db.transaction(function (tx) {
    tx.executeSql('select * from Readings where Date ='+"'"+day+"'", [], getReadings, errorCB);

})
}



function errorCB(err) {
alert("Error processing SQL: "+err.code);
}



var q = "'"; //quotes
var bt = " between ";
var equals = "=";
var from = ">=";
var upto = "<=";
var and = " and ";
var or = " or ";
var ch = "Chapter";
var vr = "Verse";
var op = "(";
var cp = ")";
var base = 'select * from Content where Book=';
var reading;
var readingID;





function getReadings(tx, results) {
    var items = results.rows.item(0);
    var columns = {FirstReading : 'First Reading', Psalm : 'Psalm', SecondReading : 'Second Reading', Gospel:'Gospel'};
    var day = items.Day
    var textDay= '<h1 id="day">' + day + '</p> <h2 id="title"></h2><div id="readings"></div>  <h2 id="title"></h2><div id="readings"></div>  <h2 id="title"></h2><div id="readings"></div>  <h2 id="title"></h2><div id="readings"></div>' ;                                 //day title
    document.getElementById("deviceready").innerHTML = textDay;
    for(key in columns){
        if (items[key]){                                                   //readings loop
            reading = items[key];
            readingID = key;
            var readingTitle = columns[key];
            var bookname = reading.match(/(\d )?[A-z]+/)[0];
            var book = getBookNb(bookname);
            var unclean_chapters = reading.match(/\d+:/g);
            var chapters = clean(unclean_chapters);
            var b = reading.split(":");
            var sqlselect = base + book + and;                     //select book
            for(var i=1; i < b.length; i++){                               //chapters loop
                var chapter = chapters[i-1];
                if (i != 1){
                    sqlselect += or;
                }
                sqlselect += op + ch + equals + chapter + and + op;//select chapter
                var sp = b[i].split(",");
                var dd; //double-dash
                for (v in sp){                                     
                    var verse = sp[v].match(/\d+(-\d+)?/)[0];              //verses loop
                    if (v != 0){
                        sqlselect += or;
                    }
                    if (dd === true){
                        dd = false;// unset dd
                        sqlselect += op + vr + upto + verse + cp;     //select verse before double-dash w/pattern (Nb--)
                        continue;
                    }
                    alert("it stops after this");
                    if (sp[v].includes("--")){                     
                        dd = true;// set dd for next verse upto (--verse)
                        sqlselect += op + vr + from + verse + cp;     //select verse after double-dash w/pattern (--Nb)
                        continue;
                        alert("this message is not displayed");
                    }
                     
                    if (sp[v].includes("-")){
                        var vs = verse.split("-");
                        sqlselect += op + vr + bt + vs[0] + and + vs[1] + cp;//select verses between w/pattern (Nb-Nb) 
                        continue;
                    }
                    sqlselect += op + vr + equals + verse + cp;                   //select single verse (Nb,)
                }
                sqlselect += cp + cp;
                
            }
            tx.executeSql(sqlselect, [], queryD, errorCB);     ; // get readings  from database
            document.getElementById("title").innerHTML = readingTitle + " (" + reading + ")";
            document.getElementById("title").id =  readingID;

        }
    }
   
}


 function queryD(tx, results) {
    var text ='<div class="outer">';
    var len = results.rows.length;
    for (var i = 0; i < len; i++) {
    text +=
    '<div class="chunk">'+
    '<div class="foreign">'+
    results.rows.item(i).Original +
    '</div>'+
    '<div class="translation">'+
    results.rows.item(i).Translation +
    '</div>'+
    '<div class="pronunciation">'+
    results.rows.item(i).Pronunciation +
    '</div>'+
    '</div>';
    var book = results.rows.item(i).Book;
    }
    text +="</div>";
       
    if (book<=39){
    document.getElementById("readings").dir = "rtl";
    }
    document.getElementById("readings").innerHTML = text;
    document.getElementById("readings").id = readingID;
}
    

function clean(unclean) { //helper function to clean spaces and colons
    var cleaned = [];
    for (item in unclean){
        cleaned.push(unclean[item].replace(/\s|:/g,""));    
    }
    return cleaned;
}
    
function getBookNb(key){  //helper function to get bookname
    var booknames = {
        'Genesis':1,
        'Exodus':2,
        'Leviticus':3,
        'Numbers':4,
        'Deuteronomy':5,
        'Joshua':6,
        'Judges':7,
        'Ruth':8,
        '1 Samuel':9,
        '2 Samuel':10,
        '1 Kings':11,
        '2 Kings':12,
        '1 Chronicles':13,
        '2 Chronicles':14,
        'Ezra':15,
        'Nehemiah':16,
        'Esther':17,
        'Job':18,
        'Psalms':19,
        'Proverbs':20,
        'Ecclesiastes':21,
        'Sirach':21,
        'Solomon':22,
        'Isaiah':23,
        'Jeremiah':24,
        'Lamentations':25,
        'Ezekiel':26,
        'Daniel':27,
        'Hosea':28,
        'Joel':29,
        'Amos':30,
        'Obadiah':31,
        'Jonah':32,
        'Micah':33,
        'Nahum':34,
        'Habakkuk':35,
        'Zephaniah':36,
        'Haggai':37,
        'Zechariah':38,
        'Malachi':39,
        'Matthew':40,
        'Mark':41,
        'Luke':42,
        'John':43,
        'Acts':44,
        'Romans':45,
        '1 Corinthians':46,
        '2 Corinthians':47,
        'Galatians':48,
        'Ephesians':49,
        'Philippians':50,
        'Colossians':51,
        '1 Thessalonians':52,
        '2 Thessalonians':53,
        '1 Timothy':54,
        '2 Timothy':55,
        'Titus':56,
        'Philemon':57,
        'Hebrews':58,
        'James':59,
        '1 Peter':60,
        '2 Peter':61,
        '1 John':62,
        '2 John':63,
        '3 John':64,
        'Jude':65,
        'Revelation':66,
    };
    
    return booknames[key];
}

```
`

**Comment by ghost** [comment]
I found two mistakes and possible the reason for the overload (just the asynchronicity of JavaScript);
the solution to the 2 mistakes was changing the 2 `if (sp[v].includes("-")){` to `if (sp[v].indexOf('--') !== -1){`  since Cordova doesn't support `str.includes`.
Any help dealing with the asynchronicity would also be helpful - I guess some sort of promise, but I'm guessing it's not supported.

**Comment by brody2consult** [comment]
Hi @mlochd,

My apologies for the delay.

Looking at your code it seems to use the standard Web SQL transaction API correctly (I did not proofread your code any further than this). You have a couple places where a tx.executeSql success callback request would request one or more further SELECT statements to be executed.

The one thing to look out for is if you do something with the tx object after a timeout, AJAX GET, etc. This would be incorrect since the tx object would generally be finalized before you do something else with it. For more details: http://www.brodybits.com/cordova/sqlite/api/jquery/2015/10/26/populating-cordova-sqlite-storage-with-the-jquery-api.html

I do have a promise helper at <https://github.com/brodybits/sql-promise-helper> which is meant to help with some specific calls but could also help your case. I will improve the documentation of this when I get a chance someday.

The advantage of the way your code uses the transaction API is that it blocks other transactions and would be atomic.

**Comment by ghost** [comment]
Hartstikke bedankt Chris!


I appreciate the long answer... I will let you know when the bible and mass-readings app is done, since it will be open source, maybe with a donation (probably not very useful to you though - since you're probably not very "religious").


It is already partly loading now  (as an apk on Android) on some of the days for the readings. I think it is just the next loops catching up and changing the variables before it has time to even load, since Java Script is asynchronous.  Thanks for the tips (the AJAX GET, the promise plugin, and the documentation). Before I try the promise (which adds some more complexity), since I am still very new to JavaScript, I think I will first see if I can loop the sql requests as a self-callbacks instead of through the for loops, maybe by passing in an extra argument.


All the best to your great open source contributions!  And thanks again!


Martin

        Vrolijk Kerstfeest! ...if you celebrate


________________________________

**Comment by ghost** [comment]
Hi Chris, it up at https://play.google.com/store/apps/details?id=areopagitics.DailyScrolls


Thanks again for the great plugin!

Daily Scrolls - Android Apps on Google Play<https://play.google.com/store/apps/details?id=areopagitics.DailyScrolls>
play.google.com
Catholic Mass Readings and Bible in interlinear Greek and Hebrew




________________________________

**Comment by brody2consult** [comment]
Thanks @mlochd. Can I reference the app in README.md?

**Comment by ghost** [comment]
Sure! Thanks again! Works like a charm... It does take about second or two to load.... but it is a lot of requests on the other hand...

On Dec 22, 2016 11:06 AM, "Christopher J. Brody" <notifications@github.com> wrote:

Thanks @mlochd<https://github.com/mlochd>. Can I reference the app in README.md?

**Comment by brody2consult** [comment]
I added your app as a sample in README.md, I hope it is OK. Thanks!
