### ISSUE TITLE
Export db to sql

### ISSUE THREAD

**Issue by estvmachine** [brody2consult/cordova-sqlite-ext#57]
This actually works for export db, but  i really want to export the db like sql query, you know a way to do that. I try with this plugin https://github.com/dpa99c/cordova-sqlite-porter.

```javascript
$cordovaFile.copyFile( 'cordova.file.applicationStorageDirectory', 'demo.db', cordova.file.externalDataDirectory, 'newDb.db').then(
   ....
);

```

**Comment by brody2consult** [comment]
Will be answered in litehelpers/Cordova-sqlite-help#27 when I get a chance.
