### ISSUE TITLE
error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found

### ISSUE THREAD

**Issue by tuanbs** [brody2consult/cordova-sqlite-ext#60]
Hi, I got the following error when building the app for windows platform on Windows 10 using VS 2017 community:
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\WorkspaceWin\TestRepos\sideMenuSample\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
> Command finished with error code 1: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe C:\WorkspaceWin\TestRepos\sideMenuSample\platforms\windows\CordovaApp.Windows10.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configuration=debug,/p:Platform=x64

It works fine with iOS and Android platforms. I can build and run the sample side-menu template of Ionic 1 framework with Windows platform. But when I added this plugin it raised the above error. I followed the section 'Windows platform notes' but still no luck.

**Comment by tuanbs** [comment]
Hi, I fixed this issue by installing VS 2015 Update 3 and select option UWP Tools during installation. The thing is I'm using VS 2017, I don't need VS 2015 which takes 15 Gb after installation. I tried the other methods to install v140 build tools separately to save disk space such as installing the VC++ 2015.3 toolset, but no luck. I referred to [this site](https://developercommunity.visualstudio.com/content/problem/48806/cant-find-v140-in-visual-studio-2017.html) which says that I need VS 2015 Update 3 installed and it really fixed this issue. But it doesn't make any sense to install a massive VS 2015 IDE to fix an issue. Is there any better solution to fix this issue without installing VS 2015? Thanks.

**Comment by brody2consult** [comment]
> I referred to this site which says that I need VS 2015 Update 3 installed and it really fixed this issue.

<https://developercommunity.visualstudio.com/content/problem/48806/cant-find-v140-in-visual-studio-2017.html>

Thanks @tuanbs that looks like the correct workaround. This plugin version will be updated to use build tools v141 in the near future. Marked as a bug.

**Comment by tuanbs** [comment]
Thanks @brodybits to take it into account. Hope it could be fixed ASAP as it doesn't make sense to fix it by installing the massive VS 2015 (which takes space of more 10 Gb) while using VS 2017.

**Comment by brody2consult** [comment]
This plugin version is now updated to support VS 2017 with v141 build tools, workaround to use old build tools (v140) in VS 2017 is no longer needed. Thanks @tuanbs for your patience.
