### ISSUE TITLE
error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by JeongJun-Lee** [brody2consult/cordova-sqlite-ext#69]
I installed cordova-sqlite-ext plugin for Pre-Populated database and also installed this cipher-adapter for reading ciphered database.

When I do "ionic cordorva build android" at Ionic, the cipher-adapter's build fails.

BUILD FAILED

    Total time: 1.25 secs
    Error: /Users/comseong/dev/ionic3/myApp-tab/platforms/android/gradlew: Command failed with exit code 1 
    Error output:
    /Users/comseong/dev/ionic3/myApp-tab/platforms/android/src/io/sqlc/SQLiteConnectorDatabase.java:55: 
    error: method does not override or implement a method from a supertype
         @Override
         ^
    /Users/comseong/dev/ionic3/myApp-tab/platforms/android/src/io/sqlc/SQLiteConnectorDatabase.java:77: 
    error: method does not override or implement a method from a supertype
         @Override
         ^
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: /Users/comseong/dev/ionic3/myApp-tab/platforms/android/src/cordova/plugins/Diagnostic.java uses 
    unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    2 errors
    
    FAILURE: Build failed with an exception.

**Comment by JeongJun-Lee** [comment]
I don't know why this issue would be solved, but after I uninstalled all plug-ins and did cordova build whenever each one re-installed.

**Comment by JeongJun-Lee** [comment]
I confirmed to open plain db normally with only cordova-sqlite-ext.
But after installed additionally cordova-sqlcipher-adapter., when I tried to open a encrypted db with key option by below code,

private options = { name: 'pos.db', key: 'test', location: 'default', createFromLocation: 1 };
this.sqlite.create(this.options).then((db: SQLiteObject) => {...}

it returns db open failed error like below.
![image](https://user-images.githubusercontent.com/11474775/32686582-bb64a116-c6c8-11e7-9ccc-a476afd74beb.png)

Do I have a method to debug more? Even when I tried to open a plain db without key options after removing encryption from db file, the same error comes out.

**Comment by JeongJun-Lee** [comment]
I saw this statement, "Pre-populatd DB is NOT supported by this version" in the Readme of cordova-sqlcipher-adapter.

In that case, this issue is meaningless? Is there any method that I can utilize the encrypted pre-populated db file?

Thanks.

**Comment by brody2consult** [comment]
My apologies for the delay. This kind of thing may happen if you have
multiple sqlite plugins installed, or if you have a combination of sqlite
and sqlcipher plugins.

I would recommend that you start with a clean project, add and one more
plugin at a time, test build after adding each one.

I've been extremely busy with work projects, hope to look at this in a
couple weeks or so.

**Comment by JeongJun-Lee** [comment]
Thank you for your effort even though you're really busy.
I posted new [issue](https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/58) I've met when I tried to read the encrypted pre-populated db file?

When you get some another free time, if you check this, I'll be very happy:)
