### ISSUE TITLE
New android apk does not update the device db. Is this normal?

### ISSUE THREAD

**Issue by nfuria** [brody2consult/cordova-sqlite-ext#76]
I published an app some time ago. Today I upload a new apk where only the db is updated. 
The device updated app downloaded from Play Store continues using the same old db.
To resolve I changed the name of the db file.
The question: are there some configuration to force the substitution of the db file in the device?

Thanks

Furia

**Comment by nfuria** [comment]
I did not read all the issues carefully.
The # 68 issue addressed the same problem and had already been answered, proposing the solution that I used.
Sorry...

**Comment by brody2consult** [comment]
Thanks @nfuria, adding pointer to litehelpers/cordova-sqlite-ext#68 for reference
