### ISSUE TITLE
IOS Shared App Group, how to?

### ISSUE THREAD

**Issue by raphrmx** [brody2consult/cordova-sqlite-ext#77]
Hello and congratulate for your work,

Would it be possible to get a functional version for ios shared app group?
I try to run this version but I can not :(

this is my code but my database is not in the shared app group

`this.db = sqlitePlugin.openDatabase({name: 'tich.sqlite', iosDirectoryURL:'group.be.tich'})`

With the master version, it works but the database is not in the group folder.

With the contrib-ios-shared1 version it gives me the error: "I need to open the database before executing a transaction. Yet she is open."

Do you have an idea of the version I need to use and the settings I need to use?

Thank you so match in advance,
Raph :-)

Edit: My application have the capabilities App Groups group.be.tich in Xcode and `<preference name="SqliteExtAppGroupId" value="group.be.tich" />` in config.xml

**Comment by raphrmx** [comment]
No idea? :'(

**Comment by brody2consult** [comment]
My apologies for the delay, can take a look after I deliver the major release in June 2018 (litehelpers/Cordova-sqlite-storage#773). Until then I suggest you use the contribution in #75. Please request help there or in [litehelpers / Cordova-sqlite-help / issues](https://github.com/litehelpers/Cordova-sqlite-help/issues).
