### ISSUE TITLE
issues in windows UWP

### ISSUE THREAD

**Issue by jhjulkun** [brody2consult/cordova-sqlite-ext#78]
Hi

Great plugin! Have been using it in iOS and Android, thanks!
However, when trying it in windows, I get 'errors with executeSQL'

Any known problems in windows ? 
I should be able to provide a small testcase if needed. 

Thanks
/ Heikki

![sql-err](https://user-images.githubusercontent.com/2847796/37873678-e7e1d1a6-3021-11e8-979f-c571dc87b81c.jpg)

**Comment by jhjulkun** [comment]
Btw, seems like the latest version of iOS does NOT support blobs, 
is this the case for the windows version too ? 

I'm trying to use a mbtiles.db for leaflet for offline usage.

**Comment by brody2consult** [comment]
It is recommended to use HEX or BASE64 function to select BLOB values, as documented.
