### ISSUE TITLE
Error publishing to the Windows Store

### ISSUE THREAD

**Issue by jdnichollsc** [brody2consult/cordova-sqlite-ext#8]
Hi man,

See please an error validating the app before to publish to the store http://screencast.com/t/vuE0x5gdtV

What do you think? Thanks for all! :dancers:

**Comment by brody2consult** [comment]
Please apply the changes from the commit at: 863a0e611007fa4fdae03e6494fe0419c0743927

I will merge it when I get a chance. It may be a few weeks.

ref: litehelpers/Cordova-sqlite-storage#384

Thanks for reporting.

**Comment by jdnichollsc** [comment]
Works perfect! Thanks my friend! :dancers:

**Comment by brody2consult** [comment]
863a0e6 is now merged, closing

**Comment by jdnichollsc** [comment]
Thanks!
